### ISSUE TITLE
Errors when going to settings for the first time

### ISSUE THREAD

**Issue by nlrb** [MikeOne/nl.kikkert.plex#1]
Once:
Error: Cannot find module './utils'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/node_modules/plex-api/node_modules/request/node_modules/http-signature/lib/parser.js:5:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

And 6 times:
Getting Plex servers
TypeError: Cannot read property 'api' of undefined
    at module.exports.fn (/api.js:53:39)
    at /opt/homey-client/system/types/manager/apps/bootstrap/homey-app/manager/api.js:1:350
    at Array.some (native)
    at /opt/homey-client/system/types/manager/apps/bootstrap/homey-app/manager/api.js:1:229
    at /opt/homey-client/system/types/manager/apps/bootstrap/homey-app/helpers/client.js:1:852
    at Array.forEach (native)
    at process.<anonymous> (/opt/homey-client/system/types/manager/apps/bootstrap/homey-app/helpers/client.js:1:821)
    at process.emit (events.js:110:17)
    at handleMessage (child_process.js:324:10)
    at Pipe.channel.onread (child_process.js:352:11)

**Comment by michielkikkert** [comment]
Hey cool, my first issue, thanks!

Can you please elaborate on the steps to reproduce this? Also, did you managed to get the settings page and the app to work at all? Where did you see this output? in the athom-cli window or in the browser console? Homey version used?

**Comment by nlrb** [comment]
You're welcome :-). I use it as an example to learn how to make an Homey app.

Steps taken:
- Clone git repo
- athom project --run nl.kikkert.plex
- Go straight to the settings page

Homey FW version used: 0.8.17. After the errors I tried to press a button in the settings page, but no response at all (just the same error). Errors are from the CLI window.

From the console:
http://192.168.1.82/api/app/nl.kikkert.plex/getSettings?_=1455448885930 Failed to load resource: net::ERR_EMPTY_RESPONSE
(index):54 error Could not get settings from server
http://192.168.1.82/api/app/nl.kikkert.plex/getPin/?_=1455448892932 Failed to load resource: net::ERR_EMPTY_RESPONSE
(index):105 Uncaught TypeError: Cannot read property 'code' of null(anonymous function) @ (index):105i.onerror @ api.js:1
http://192.168.1.82/api/app/nl.kikkert.plex/getPlexServers?_=1455448885430 Failed to load resource: net::ERR_EMPTY_RESPONSE
http://192.168.1.82/api/app/nl.kikkert.plex/getPlexPlayers?_=1455448885430 Failed to load resource: net::ERR_EMPTY_RESPONSE

**Comment by michielkikkert** [comment]
Okay thanks, I will attempt to recreate and will let you know.

**Comment by michielkikkert** [comment]
oh by the way - what did the cli console say? Right after the upload?
This is what it says here after a clean reset of homey:

Uploading to 192.168.2.35:80...
Running `nl.kikkert.plex`...
Debugging...
Plex app doesn't have any setup yet..Visit the settings page on your Homey!
Hello, Homey user

**Comment by nlrb** [comment]
athom project --run nl.kikkert.plex/
Archiving...
Uploading to 192.168.1.82:80...
Running `nl.kikkert.plex`...
Debugging...
Error: Cannot find module './utils'
...

**Comment by michielkikkert** [comment]
Got it! I re-cloned the git repo and found the same issue. It seems there was a gitignore somewhere that prevented my entire project to be synced to github. I think I fixed it now. Go to your nl.kikkert.plex folder and run a git pull - that should clone a whole bunch of additional files.

Once done, athom project --run

**Comment by nlrb** [comment]
Yes, that fixed it!

**Comment by michielkikkert** [comment]
Excellent. If you find more, please report!
